### ISSUE TITLE
Image problem

### ISSUE THREAD

**Issue by camol** [dicom/ruby-dicom#49]
Hi in my irb I'm doing:

```
dcm = DICOM::DObject.read(dicom_path)
```

and object is ok initiated. But when I try dcm.image I get false. Please help

**Comment by supertracer** [comment]
as instructed i am able to convert via terminal using command convert IM-0001-0001.dcm image.jpg,   
but when i run it with the gem it throws error  LoadError: cannot load such file -- rmagick
I have added a question on stack overflow with details [here](http://stackoverflow.com/questions/35503020/loaderror-cannot-load-such-file-rmagick-with-dicom-gem?noredirect=1#comment58701914_35503020)

**Comment by dicom** [comment]
@supertracer Thank you for reporting your issue.

Can you try the following in two separate irb sessions on your system:

require 'rmagick'

require 'RMagick'

Does one, both or none of these succeed?!

If the first one fails, can you please report your windows, ruby and rmagick versions.

**Comment by supertracer** [comment]
when i use require 'rmagick' , it doesn't even read the dcm file.
Using 'RMagick' ,reads the dcm file successfully but gives error DICOM: Decompressing pixel values has failed (unsupported transfer syntax: '1.2.840.10008.1.2.4.91' - JPEG 2000 Image Compression)
Using mini_magick, converts the dicom image to jpg, but the jpg file is not readable.


My system configurations: OS :Ubuntu 14.04,Ruby: 2.2.2p95 , RMagick:  rmagick (2.13.2)

**Comment by supertracer** [comment]
When i use include Magick , instead of DICOM.image_processor = :rmagick gives error 
cannot load such file -- rmagick

**Comment by dicom** [comment]
Regarding the case sensitivity problems ('RMagick' vs 'rmagick'), you should upgrade to rmagick 2.13.4 (or later).

Regarding the failure to decompress the image data, this is usually because image magick is not able to handle the particular jpeg compression variant. However, from your case, it seems you are able to succeed with the convert command, so that makes it somewhat surprising. 

I wonder if you can try this again with a newer version of rmagick, and if it still fails like this, if you can send me this dicom file.

**Comment by supertracer** [comment]
Thanks the problem is fixed by upgrading to the newest version of RMagick

**Comment by dicom** [comment]
Im happy to hear that.

It would be great if you could post an update on the stackoverflow link above that your issue was fixed by upgrading rmagick to 2.13.4 or later.
