### ISSUE TITLE
Support "1.2.840.10008.1.2.4.90" transfer syntax

### ISSUE THREAD

**Issue by elsurudo** [dicom/ruby-dicom#58]
I am finding that images with this transfer syntax cannot be loaded:

`WARN: DICOM: Decompressing pixel values has failed (unsupported transfer syntax: '1.2.840.10008.1.2.4.90' - JPEG 2000 Image Compression (Lossless Only))`

Any tips on how to handle this situation?

It is a valid transfer syntax acocrding to: http://www.dicomlibrary.com/dicom/transfer-syntax/

**Comment by dicom** [comment]
Hi Ernest

Thank you for reporting this issue.

This is a known limitation with ruby-dicom, or rather, with image magick.

What happens in your case, is that ruby-dicom is able to parse the DICOM file perfectly fine, but it is not able to decompress the pixel data, because it doesn't know how to do it with that compression. Ruby-dicom relies on RMagick to decode any jpeg compressed data, and if RMagick is not able to do it on your system, then ruby-dicom fails to get the pixel data.

This has already been discussed in a previous issue (please refer to it for further details):
https://github.com/dicom/ruby-dicom/issues/45

Best regards,
Chris
